package rpc;/*
 * Automatically generated by jrpcgen 1.1.3 on 16-12-16 ����10:24
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "rpc" ONC/RPC program.
 */
public interface rpc {
    public static final int TEST_RPC_FUNCTION_VERSION = 1;
    public static final int getImg_1 = 1;
    public static final int TEST_RPC_FUNCTION_NUMBER = 0x20000001;
    public static final int MAXNAMELEN = 2048;
    public static final int getFileTree_1 = 2;
}
// End of rpc.java
