/*
 * Automatically generated by jrpcgen 1.1.3 on 16-12-16 ÏÂÎç10:24
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

/**
 * The class <code>rpcClient</code> implements the client stub proxy
 * for the TEST_RPC_FUNCTION_NUMBER remote program. It provides method stubs
 * which, when called, in turn call the appropriate remote method (procedure).
 */
public class rpcClient extends OncRpcClientStub {

    /**
     * Constructs a <code>rpcClient</code> client stub proxy dummy.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rpcClient() throws OncRpcException, IOException {
        super(null);
    }

    /**
     * Constructs a <code>rpcClient</code> client stub proxy object
     * from which the TEST_RPC_FUNCTION_NUMBER remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rpcClient(InetAddress host, int protocol)
           throws OncRpcException, IOException {
        super(host, rpc.TEST_RPC_FUNCTION_NUMBER, 1, 0, protocol);
    }

    /**
     * Constructs a <code>rpcClient</code> client stub proxy object
     * from which the TEST_RPC_FUNCTION_NUMBER remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rpcClient(InetAddress host, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, rpc.TEST_RPC_FUNCTION_NUMBER, 1, port, protocol);
    }

    /**
     * Constructs a <code>rpcClient</code> client stub proxy object
     * from which the TEST_RPC_FUNCTION_NUMBER remote program can be accessed.
     * @param client ONC/RPC client connection object implementing a particular
     *   protocol.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rpcClient(OncRpcClient client)
           throws OncRpcException, IOException {
        super(client);
    }

    /**
     * Constructs a <code>rpcClient</code> client stub proxy object
     * from which the TEST_RPC_FUNCTION_NUMBER remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rpcClient(InetAddress host, int program, int version, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, 0, protocol);
    }

    /**
     * Constructs a <code>rpcClient</code> client stub proxy object
     * from which the TEST_RPC_FUNCTION_NUMBER remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public rpcClient(InetAddress host, int program, int version, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, port, protocol);
    }

    /**
     * Call remote procedure getImg_1.
     * @param arg1 parameter (of type String) to the remote procedure call.
     * @return Result from remote procedure call (of type RpcBitmap).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public RpcBitmap getImg_1(String arg1)
           throws OncRpcException, IOException {
        XdrString args$ = new XdrString(arg1);
        RpcBitmap result$ = new RpcBitmap();
        client.call(rpc.getImg_1, rpc.TEST_RPC_FUNCTION_VERSION, args$, result$);
        return result$;
    }

    /**
     * Call remote procedure getFileTree_1.
     * @return Result from remote procedure call (of type String).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public String getFileTree_1()
           throws OncRpcException, IOException {
        XdrVoid args$ = XdrVoid.XDR_VOID;
        XdrString result$ = new XdrString();
        client.call(rpc.getFileTree_1, rpc.TEST_RPC_FUNCTION_VERSION, args$, result$);
        return result$.stringValue();
    }

}
// End of rpcClient.java
